test:
 optimist: hello world
server:
 port: 8013
#eureka:
# client:
#  register-with-eureka: true
#  fetch-registry: true
#  service-url:
#   defaultZone: http://localhost:7001/eureka/
spring:
 application:
  name: service-order
 cloud:
  zookeeper:
   connect-string: localhost:2181
#设置feign客户端超时时间（OpenFeign集成了Ribbon，超时由ribbon控制）
ribbon:
 #指的是建立连接后从服务器读取到可用资源所用的时间
 ReadTimeout:  5000
 #指的是建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间
 ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true #开启自身容错

