server:
  port: 8111
spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:optimist-du/springcloud-config.git
          search-paths: #读取目录
            - springcloud-config
      label: master #读取分支
config:
  info: git@github.com:optimist-du/springcloud-config.git11
